name: test
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:   [ 'ubuntu', 'macos' ]
    steps:
      - uses: crystal-lang/install-crystal@v1
      - uses: actions/checkout@v3
      - run: |
          git clone https://github.com/jtanx/libclipboard
          cd libclipboard
          cmake -DBUILD_SHARED_LIBS=ON .
          make -j4
          sudo make install
      - run: shards install
      - run: crystal spec
